import Head from 'next/head';
import Button from '@/components/ui/Button/Button';
import Spinner from '@/components/ui/Spinner/Spinner';
import ScrollShadow from '@/components/ui/ScrollShadow/ScrollShadow';
import Input from '@/components/ui/Input/Input';
import TextArea from '@/components/ui/TextArea/TextArea';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Input type="text" name="name" radius="medium" />
        <Input type="password" name="password" radius="medium" />
        <TextArea name="message" />

        <Button label="click" onClick={() => console.log('Clicked')} />
      </main>
    </>
  );
}
